name: CI
on:
  push:
    tags:
      -  '[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }} 
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
                Changes in this Release
                - Release ${{ github.ref }} 
            draft: false
            prerelease: false
      - name: Validate CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPOD_PASSWORD_LOGIN }}
        run: |
          pod spec lint Podspec/MapZone/MapZone.podspec --allow-warnings
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPOD_PASSWORD_LOGIN }}
        run: |
          pod trunk push Podspec/MapZone/MapZone.podspec --allow-warnings